apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-9antrakids-backend
  labels:
    app: e-9antrakids-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: e-9antrakids-backend
  template:
    metadata:
      labels:
        app: e-9antrakids-backend
    spec:
      containers:
        - name: backend
          image: altiplanooo/e-9antra_kids-backend:1.0.%BUILD_NUMBER%
          ports:
            - containerPort: 8094
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://e-9antrakids-mysql:3306/demopfe
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
---
apiVersion: v1
kind: Service
metadata:
  name: e-9antrakids-backend
spec:
  selector:
    app: e-9antrakids-backend
  ports:
    - port: 8094
      targetPort: 8094
  type: ClusterIP

