apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: e-9antrakids-mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage
