apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  mysql-root-password: root
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: e-9antrakids-mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-9antrakids-mysql
  labels:
    app: e-9antrakids-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: e-9antrakids-mysql
  template:
    metadata:
      labels:
        app: e-9antrakids-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              value: demopfe
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-storage
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: e-9antrakids-mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: e-9antrakids-mysql
spec:
  selector:
    app: e-9antrakids-mysql
  ports:
    - port: 3306
      targetPort: 3306
  clusterIP: None



